<?php

declare(strict_types=1);

return [
    'path' => 'packages',
    'replacements' => [
        'author_email' => 'jesseberkhof95@gmail.com',
        'author_name' => 'Jesse Berkhof',
        'author_role' => 'Developer',
        'package_description' => 'This package has been auto-generated by Arctic',
        'namespace' => 'Arctic',
    ],
    'files' => [
        '/composer.json',
        '/src/config/package.php',
        '/src/ClassName.php.stub',
        '/src/ClassNameFacade.php.stub',
        '/src/ClassNameServiceProvider.php.stub',
    ]
];
